// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Olimpo.ProductAPI.Model.Context;

#nullable disable

namespace Olimpo.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20260117013714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Olimpo.ProductAPI.Model.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 1, 17, 1, 37, 14, 574, DateTimeKind.Utc).AddTicks(2613),
                            Description = "Produtos eletrônicos em geral",
                            IsActive = true,
                            Name = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 1, 17, 1, 37, 14, 574, DateTimeKind.Utc).AddTicks(2615),
                            Description = "Vestuário e acessórios",
                            IsActive = true,
                            Name = "Roupas"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 1, 17, 1, 37, 14, 574, DateTimeKind.Utc).AddTicks(2617),
                            Description = "Livros físicos e digitais",
                            IsActive = true,
                            Name = "Livros"
                        });
                });

            modelBuilder.Entity("Olimpo.ProductAPI.Model.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            CreatedAt = new DateTime(2026, 1, 17, 1, 37, 14, 574, DateTimeKind.Utc).AddTicks(2721),
                            Description = "Notebook de alta performance para jogos",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsActive = true,
                            Name = "Notebook Gamer",
                            Price = 4999.90m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            CreatedAt = new DateTime(2026, 1, 17, 1, 37, 14, 574, DateTimeKind.Utc).AddTicks(2723),
                            Description = "Camiseta 100% algodão",
                            ImageUrl = "https://via.placeholder.com/300",
                            IsActive = true,
                            Name = "Camiseta Básica",
                            Price = 49.90m,
                            Stock = 50
                        });
                });

            modelBuilder.Entity("Olimpo.ProductAPI.Model.Entities.Product", b =>
                {
                    b.HasOne("Olimpo.ProductAPI.Model.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Olimpo.ProductAPI.Model.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
